### ISSUE TITLE
marc 1.0.4 test suite fails with ruby 3.0 due to keyword separation

### ISSUE THREAD

**Issue by mtasaka** [ruby-marc/ruby-marc#68]
Besides the issue with `rexml` dependency issue ( #67 ), marc 1.0.4 test suite fails with ruby 3.0: 

```
+ ruby -Ilib:. -e 'gem "test-unit"; require "marc" ; Dir.glob("test/tc_*.rb"){|f| require f }'
Loaded suite -e
Started
...
Test not being run from JRuby, skipping jrexml convenience method test.
.
Test not being run from JRuby, skipping 'test_set_jrexml'.
.
Test not being run from JRuby, skipping 'test_set_jstax'.
.
Testing 'test_set_magic' for parser: Nokogiri::XML::SAX::Parser
......................E
===============================================================================
Error: test_unicode_forgiving_reader_passes_options(ReaderCharEncodingsTest): NoMethodError: undefined method `[]' for nil:NilClass
/builddir/build/BUILD/marc-1.0.4/usr/share/gems/gems/marc-1.0.4/test/tc_reader_char_encodings.rb:44:in `assert_cp866_right'
/builddir/build/BUILD/marc-1.0.4/usr/share/gems/gems/marc-1.0.4/test/tc_reader_char_encodings.rb:103:in `test_unicode_forgiving_reader_passes_options'
     100: 
     101:       record = reader.first 
     102: 
  => 103:       assert_cp866_right(record, "UTF-8")
     104:     end
     105:   
     106:     def test_explicit_encoding
===============================================================================
...E
===============================================================================
Error: test_with_transcode(ReaderCharEncodingsTest): TypeError: no implicit conversion of Hash into String
/builddir/build/BUILD/marc-1.0.4/usr/share/gems/gems/marc-1.0.4/lib/marc/reader.rb:446:in `encode'
/builddir/build/BUILD/marc-1.0.4/usr/share/gems/gems/marc-1.0.4/lib/marc/reader.rb:446:in `set_encoding'
/builddir/build/BUILD/marc-1.0.4/usr/share/gems/gems/marc-1.0.4/lib/marc/reader.rb:372:in `block in decode'
/builddir/build/BUILD/marc-1.0.4/usr/share/gems/gems/marc-1.0.4/lib/marc/reader.rb:339:in `upto'
/builddir/build/BUILD/marc-1.0.4/usr/share/gems/gems/marc-1.0.4/lib/marc/reader.rb:339:in `decode'
/builddir/build/BUILD/marc-1.0.4/usr/share/gems/gems/marc-1.0.4/lib/marc/reader.rb:283:in `decode'
/builddir/build/BUILD/marc-1.0.4/usr/share/gems/gems/marc-1.0.4/lib/marc/reader.rb:233:in `block in each'
/builddir/build/BUILD/marc-1.0.4/usr/share/gems/gems/marc-1.0.4/lib/marc/reader.rb:273:in `each_raw'
/builddir/build/BUILD/marc-1.0.4/usr/share/gems/gems/marc-1.0.4/lib/marc/reader.rb:232:in `each'
/builddir/build/BUILD/marc-1.0.4/usr/share/gems/gems/marc-1.0.4/test/tc_reader_char_encodings.rb:245:in `first'
/builddir/build/BUILD/marc-1.0.4/usr/share/gems/gems/marc-1.0.4/test/tc_reader_char_encodings.rb:245:in `test_with_transcode'
     242:         :external_encoding => 'cp866', 
     243:         :internal_encoding => 'UTF-8')
     244:       
  => 245:       record = reader.first 
     246:     
     247:       assert_cp866_right(record, "UTF-8")      
     248:       
===============================================================================
........................................Warn:  Missing indicator
......
Running test_batch with: rexml.
Running test_batch with: nokogiri.
.
Running test_leader_from_xml with: rexml.
Running test_leader_from_xml with: nokogiri.
.
Running test_non_numeric_fields with: rexml.
Running test_non_numeric_fields with: nokogiri.
.
Running test_read_no_leading_zero_write_leading_zero with: rexml.
Running test_read_no_leading_zero_write_leading_zero with: nokogiri.
.
Running test_read_string with: rexml.
Running test_read_string with: nokogiri.
.
Running test_read_write with: rexml.
Running test_read_write with: nokogiri.
.
Running test_xml_entities with: rexml.
Running test_xml_entities with: nokogiri.
.
Running test_xml_enumerator with: rexml.
Running test_xml_enumerator with: nokogiri.
.
Finished in 0.642624544 seconds.
-------------------------------------------------------------------------------
87 tests, 633 assertions, 0 failures, 2 errors, 0 pendings, 0 omissions, 0 notifications
97.7011% passed
-------------------------------------------------------------------------------
```

I don't know well about marc, however the following change seems to work, so this is due to ruby 3.0 keyword separation change: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

```
diff -urp '--exclude=*~' marc-1.0.4.orig/lib/marc/reader.rb marc-1.0.4/lib/marc/reader.rb
--- marc-1.0.4.orig/lib/marc/reader.rb	2021-01-30 20:51:28.746261429 +0900
+++ marc-1.0.4/lib/marc/reader.rb	2021-01-30 21:07:12.367242406 +0900
@@ -443,7 +443,7 @@ module MARC
         # get an exception from inside ruby-marc, and it may change
         # in future implementations. 
         if params[:internal_encoding]
-          str = str.encode(params[:internal_encoding], params)
+          str = str.encode(params[:internal_encoding], **params)
         elsif (params[:invalid] || params[:replace] || (params[:validate_encoding] == true))
 
           if params[:validate_encoding] == true && ! str.valid_encoding?
``` 

Note that ruby 2.7 already emits warnings:
```
/dir/marc-1.0.4/usr/share/gems/gems/marc-1.0.4/lib/marc/reader.rb:446: warning: Using the last argument as keyword parameters is deprecated
```

**Comment by jrochkind** [comment]
Thank you!

I was worried that this would break on older rubies... but it looks like double-splat has been supported since ruby 2.0. I'm not sure if ruby-marc currently claims to or does support rubies even older than 2.0 though? If we stop supporting older rubies, it might call for a major version release? 

Are you interested in submitting PR's for both of these ruby 3.0 issues? 

Also, ruby-marc kind of currently lacks of committed maintainers, and could use some. I am just doing my best to keep the lights on, but don't actually use ruby-marc myself currently, and don't have the time or energy to give it the attention it deserves as a maintainer. I haven't seen anyone else on the committer list participate in issues or PR's much for a while.

**Comment by cbeer** [comment]
Fixed by #69. It'd be great to get that into a new release soon.

**Comment by billdueber** [comment]
Fixed a while back.
